### ISSUE TITLE
Лишний код

### ISSUE THREAD

**Issue by agordov** [skyreaper925/mipt_lpr_cpplessons_term2#1]
https://github.com/skyreaper925/mipt_lpr_cpplessons_term2/blob/098d7fe9c75d7f84cdcf78bf5be3bc56eb44b264/week1/A.cpp#L2
Зачем два раза писать одно и то же?

**Comment by skyreaper925** [comment]
Работа программы реализована двумя разными алгоритмами (один мой, другой одногруппника). Мне понравились оба, поэтому решено их сохранить без вреда для работы программы
